### ISSUE TITLE
`Exporter::svg_path()` reported to not be closing paths

### ISSUE THREAD

**Issue by DanRathbun** [Eneroth3/eneroth-svg-exporter#2]
`Exporter::svg_path()` reported to not be closing paths. - "exporter.rb", line 151

REF: https://forums.sketchup.com/t/eneroth-svg-exporter/174017

I think that (contrary to what the OP said in post 3 of your forum topic,) line **`169`** should **remain as is**.

Line **`155`** should become ...
```ruby
   end.join(" ") << " Z"
```
... so that each loop tells the SVG path to close as it is processing **faces** (which are a set of closed edges.)

Then `d_inner` should begin with a space **if** there are inner loops, so line **`165`** should insert a leading space like:
```ruby
     d_inner[0] = " M"
```
And again, each inner loop should close it's corresponding SVG path, so line **`164`** should be:
```ruby
     end.join(" ") << " Z"
```

**Comment by Eneroth3** [comment]
Fixed. Awaiting EW review now.

Thanks for logging.
