### ISSUE TITLE
Tool usage instructions

### ISSUE THREAD

**Issue by FrankBolleri** [Eneroth3/eneroth-svg-exporter#4]
Dear Eneroth3,
for first thanks for all your work! I like your plugins, easy to install and to use.

For that reason, I am little in trouble because I do not understand exactly how to make SVG Exporter works.
I try to draw something in 2D on the horizontal plane (the one you see selecting Camera -> Standard Views -> Top).

For example:
![Screenshot 2023-12-29 at 17 39 01](https://github.com/Eneroth3/eneroth-svg-exporter/assets/26364299/75ed2fd9-967b-41f6-a51d-1215623ee458)

Then I select the objects and invoke your plugin; it ask to me filename for SVG output.
But the result is always a "blank" SVG (I have tried to check it in Google Chrome and importing into LIghtBurn software).
What I am doing wrong?

Thanks and I wish you an happy new year!
Francesco

**Comment by Eneroth3** [comment]
Hi,

Have you tried opening the file in an editor like Inkscape or a text editor? Maybe the objects are wrongly positioned or have the same color as the background.

**Comment by FrankBolleri** [comment]
Checking with a text editor, I was able to understand the issue was in dimensions.
Probably in my previous test I draw something "too big" that go out from the maximum dimensions in LightBurn.
Drawing in SketchUp paying with more attention to dimensions I get the export as I need.
![Screenshot 2024-01-04 at 00 14 38](https://github.com/Eneroth3/eneroth-svg-exporter/assets/26364299/46656206-8d53-4a24-b831-2e2f125b52e4)

What I still do not understand, but is irrelevant for my usage need (SketchUp > LightBurn), is the color management.

When you tell _have the same color as the background_, what is the color source you expect?
On svg I always get "#FFFFFF" even if faces in model are colored (as you see in previous picture).
![Screenshot 2024-01-04 at 00 17 37](https://github.com/Eneroth3/eneroth-svg-exporter/assets/26364299/480e70fc-b8da-48a7-a172-8a72ee56a22a)

Maybe this is the reason because if I open with Inkscape, I still see nothing:
![Screenshot 2024-01-04 at 00 19 00](https://github.com/Eneroth3/eneroth-svg-exporter/assets/26364299/556f080c-1e27-4eb7-a163-cf34c17fb6f4)

But if I manually alter colors in text editor:
![Screenshot 2024-01-04 at 00 21 24](https://github.com/Eneroth3/eneroth-svg-exporter/assets/26364299/8ac0072e-3bbb-4448-9dd2-adc431cd25dd)

Inkscape start to show something:
![Screenshot 2024-01-04 at 00 20 58](https://github.com/Eneroth3/eneroth-svg-exporter/assets/26364299/59b7ba69-1344-4cce-aefb-29e5f10750c7)

I attach source files if you want to check.
[Test.zip](https://github.com/Eneroth3/eneroth-svg-exporter/files/13824317/Test.zip)


Thanks
Francesco

**Comment by Eneroth3** [comment]
Have you checked if the face is reversed? Maybe the face front is white but it's the face back you are seeing.

**Comment by FrankBolleri** [comment]
The power of knowledge... yes, reversing faces it woks fine.

Thanks a lot!
Francesco
